// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kvugpttkmjyvtbfitjyg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt2dWdwdHRrbWp5dnRiZml0anlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4MDUyNzIsImV4cCI6MjA1NzM4MTI3Mn0.J4SWch-f3KDSf3wQMJnGjRIiC9yoqX436zMyp5SIlhA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);